services:
  api:
    image: "taskhelper_api"
    container_name: "TaskHelper_API"
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ../TaskHelper_API:/TaskHelper_API
    command: tail -f /dev/null